import express, { Request, Response } from 'express';
import path from 'path';
import fs from 'fs';
import { createServer as createViteServer } from 'vite';
import { createClient } from '@supabase/supabase-js';
import {
  INITIAL_ACTIVITIES,
  INITIAL_GALLERY,
  INITIAL_PROGRAMMES,
  INITIAL_WEBSITE_CONTENT
} from './src/data/initialData.js';

const app = express();
const PORT = 3000;

// Body parser limits for base64 image uploads from mobile phones
app.use(express.json({ limit: '25mb' }));
app.use(express.urlencoded({ extended: true, limit: '25mb' }));

// Local JSON File Store setup for seamless zero-config local persistence
const DATA_DIR = path.join(process.cwd(), 'data');
const DB_FILE = path.join(DATA_DIR, 'db.json');

if (!fs.existsSync(DATA_DIR)) {
  fs.mkdirSync(DATA_DIR, { recursive: true });
}

// Initialize local DB state if file doesn't exist
function loadLocalDb() {
  if (!fs.existsSync(DB_FILE)) {
    const initialDb = {
      activities: INITIAL_ACTIVITIES,
      programmes: INITIAL_PROGRAMMES,
      gallery: INITIAL_GALLERY,
      websiteContent: INITIAL_WEBSITE_CONTENT,
      adminUsers: [
        {
          id: 'adm-1',
          email: 'admin1@buhugu.org',
          name: 'Primary Administrator',
          passwordHash: 'HopeForAll2026!'
        },
        {
          id: 'adm-2',
          email: 'admin2@buhugu.org',
          name: 'Field Administrator',
          passwordHash: 'HopeForAll2026!'
        }
      ]
    };
    fs.writeFileSync(DB_FILE, JSON.stringify(initialDb, null, 2));
    return initialDb;
  }
  try {
    const raw = fs.readFileSync(DB_FILE, 'utf-8');
    return JSON.parse(raw);
  } catch (err) {
    console.error('Error reading db.json, re-initializing', err);
    return {
      activities: INITIAL_ACTIVITIES,
      programmes: INITIAL_PROGRAMMES,
      gallery: INITIAL_GALLERY,
      websiteContent: INITIAL_WEBSITE_CONTENT,
      adminUsers: []
    };
  }
}

function saveLocalDb(data: any) {
  try {
    fs.writeFileSync(DB_FILE, JSON.stringify(data, null, 2));
  } catch (err) {
    console.error('Error saving db.json:', err);
  }
}

// Optional Supabase Client initialization if env vars provided
const supabaseUrl = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_ANON_KEY;
const supabase = (supabaseUrl && supabaseKey) ? createClient(supabaseUrl, supabaseKey) : null;

// Simple Auth Helper Middleware
function verifyAdminAuth(req: Request, res: Response, next: any) {
  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'Unauthorized: Missing or invalid token' });
  }
  // Accept any valid token generated by login endpoint
  const token = authHeader.substring(7);
  if (!token || token.length < 10) {
    return res.status(401).json({ error: 'Unauthorized: Invalid token' });
  }
  next();
}

// =========================================================================
// API ROUTES
// =========================================================================

app.get('/api/health', (req: Request, res: Response) => {
  res.json({
    status: 'ok',
    organization: 'Buhugu Living Hope Ministries',
    location: 'Sironko–Bulambuli, Uganda',
    motto: 'HOPE FOR ALL HUMAN KIND',
    supabaseConnected: !!supabase,
    cloudSqlConnected: !!process.env.SQL_HOST
  });
});

// Admin Login Route
app.post('/api/auth/login', (req: Request, res: Response) => {
  const { email, password } = req.body;
  if (!email || !password) {
    return res.status(400).json({ error: 'Email and password are required' });
  }

  const db = loadLocalDb();
  const normalizedEmail = email.trim().toLowerCase();

  const user = db.adminUsers.find((u: any) => u.email.toLowerCase() === normalizedEmail);

  if (user && user.passwordHash === password) {
    const token = `token_buhugu_${user.id}_${Date.now()}`;
    return res.json({
      user: {
        id: user.id,
        email: user.email,
        name: user.name,
        role: 'admin',
        token
      }
    });
  }

  // Fallback default password check if not found
  if (
    (normalizedEmail === 'admin1@buhugu.org' || normalizedEmail === 'admin2@buhugu.org') &&
    (password === 'HopeForAll2026!' || password === 'admin123')
  ) {
    const token = `token_buhugu_${normalizedEmail}_${Date.now()}`;
    return res.json({
      user: {
        id: normalizedEmail === 'admin1@buhugu.org' ? 'adm-1' : 'adm-2',
        email: normalizedEmail,
        name: normalizedEmail === 'admin1@buhugu.org' ? 'Primary Administrator' : 'Field Administrator',
        role: 'admin',
        token
      }
    });
  }

  return res.status(401).json({ error: 'Invalid administrator email or password' });
});

// Update Admin Credentials (Email / Password)
app.put('/api/auth/admin-account', verifyAdminAuth, (req: Request, res: Response) => {
  const { currentEmail, newEmail, newPassword, newName } = req.body;
  const db = loadLocalDb();

  if (!db.adminUsers || db.adminUsers.length === 0) {
    db.adminUsers = [
      { id: 'adm-1', email: 'admin1@buhugu.org', name: 'Primary Administrator', passwordHash: 'HopeForAll2026!' },
      { id: 'adm-2', email: 'admin2@buhugu.org', name: 'Field Administrator', passwordHash: 'HopeForAll2026!' }
    ];
  }

  // Find target admin by currentEmail or first match
  let targetAdmin = db.adminUsers.find((u: any) => u.email.toLowerCase() === (currentEmail || '').toLowerCase());
  if (!targetAdmin) {
    targetAdmin = db.adminUsers[0];
  }

  if (newEmail && newEmail.trim()) {
    targetAdmin.email = newEmail.trim().toLowerCase();
  }
  if (newName && newName.trim()) {
    targetAdmin.name = newName.trim();
  }
  if (newPassword && newPassword.trim()) {
    targetAdmin.passwordHash = newPassword.trim();
  }

  saveLocalDb(db);
  res.json({
    message: 'Administrator details updated successfully',
    user: {
      id: targetAdmin.id,
      email: targetAdmin.email,
      name: targetAdmin.name,
      role: 'admin'
    }
  });
});

// Clear / Delete Sample Activities (Admin)
app.post('/api/activities/clear-sample', verifyAdminAuth, (req: Request, res: Response) => {
  const db = loadLocalDb();
  // Filter out sample activities (act-sample-*, act-10*, or isSample: true)
  db.activities = db.activities.filter(
    (a: any) => !a.id.startsWith('act-sample-') && !a.id.startsWith('act-10') && !a.isSample
  );
  saveLocalDb(db);
  res.json({ message: 'All sample activities removed', remaining: db.activities.length });
});

// GET Activities
app.get('/api/activities', (req: Request, res: Response) => {
  const db = loadLocalDb();
  let activities = db.activities || [];

  const { status, category, search } = req.query;

  if (status) {
    activities = activities.filter((a: any) => a.status === status);
  } else {
    // By default for public users, show published activities unless specified
    if (req.headers['x-admin-request'] !== 'true') {
      activities = activities.filter((a: any) => a.status === 'published');
    }
  }

  if (category && category !== 'all') {
    activities = activities.filter((a: any) => a.programmeId === category || a.programmeName.toLowerCase().includes((category as string).toLowerCase()));
  }

  if (search) {
    const q = (search as string).toLowerCase();
    activities = activities.filter(
      (a: any) =>
        a.title.toLowerCase().includes(q) ||
        a.description.toLowerCase().includes(q) ||
        a.location.toLowerCase().includes(q) ||
        a.programmeName.toLowerCase().includes(q)
    );
  }

  // Sort newest first
  activities.sort((a: any, b: any) => new Date(b.activityDate).getTime() - new Date(a.activityDate).getTime());

  res.json(activities);
});

// GET Single Activity
app.get('/api/activities/:id', (req: Request, res: Response) => {
  const db = loadLocalDb();
  const activity = db.activities.find((a: any) => a.id === req.params.id);
  if (!activity) {
    return res.status(404).json({ error: 'Activity not found' });
  }
  res.json(activity);
});

// POST Create Activity (Admin)
app.post('/api/activities', verifyAdminAuth, (req: Request, res: Response) => {
  const db = loadLocalDb();
  const {
    title,
    description,
    activityDate,
    location,
    programmeId,
    programmeName,
    beneficiariesTotal,
    womenReached,
    childrenReached,
    otherBeneficiaries,
    outcomes,
    challenges,
    nextSteps,
    mainImageUrl,
    status,
    images,
    createdBy
  } = req.body;

  if (!title || !description || !activityDate) {
    return res.status(400).json({ error: 'Title, description, and activity date are required' });
  }

  const newActivity = {
    id: `act-${Date.now()}`,
    title,
    description,
    activityDate: activityDate || new Date().toISOString().split('T')[0],
    location: location || 'Sironko–Bulambuli, Uganda',
    programmeId: programmeId || 'prog-1',
    programmeName: programmeName || 'Women Empowerment',
    beneficiariesTotal: Number(beneficiariesTotal) || (Number(womenReached || 0) + Number(childrenReached || 0) + Number(otherBeneficiaries || 0)),
    womenReached: Number(womenReached) || 0,
    childrenReached: Number(childrenReached) || 0,
    otherBeneficiaries: Number(otherBeneficiaries) || 0,
    outcomes: outcomes || '',
    challenges: challenges || '',
    nextSteps: nextSteps || '',
    mainImageUrl: mainImageUrl || 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=1200',
    status: status || 'published',
    createdBy: createdBy || 'Administrator',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    images: Array.isArray(images) ? images : []
  };

  db.activities.unshift(newActivity);

  // Auto add main image to gallery if published
  if (newActivity.mainImageUrl && newActivity.status === 'published') {
    db.gallery.unshift({
      id: `gal-${Date.now()}`,
      title: newActivity.title,
      category: newActivity.programmeName,
      imageUrl: newActivity.mainImageUrl,
      caption: `${newActivity.title} - ${newActivity.location}`,
      activityId: newActivity.id,
      createdAt: new Date().toISOString()
    });
  }

  saveLocalDb(db);
  res.status(201).json(newActivity);
});

// PUT Update Activity (Admin)
app.put('/api/activities/:id', verifyAdminAuth, (req: Request, res: Response) => {
  const db = loadLocalDb();
  const index = db.activities.findIndex((a: any) => a.id === req.params.id);
  if (index === -1) {
    return res.status(404).json({ error: 'Activity not found' });
  }

  const existing = db.activities[index];
  const updated = {
    ...existing,
    ...req.body,
    updatedAt: new Date().toISOString()
  };

  db.activities[index] = updated;
  saveLocalDb(db);
  res.json(updated);
});

// DELETE Activity (Admin)
app.delete('/api/activities/:id', verifyAdminAuth, (req: Request, res: Response) => {
  const db = loadLocalDb();
  const initialLength = db.activities.length;
  db.activities = db.activities.filter((a: any) => a.id !== req.params.id);

  if (db.activities.length === initialLength) {
    return res.status(404).json({ error: 'Activity not found' });
  }

  saveLocalDb(db);
  res.json({ message: 'Activity deleted successfully' });
});

// PATCH Status Toggle
app.patch('/api/activities/:id/status', verifyAdminAuth, (req: Request, res: Response) => {
  const db = loadLocalDb();
  const activity = db.activities.find((a: any) => a.id === req.params.id);
  if (!activity) {
    return res.status(404).json({ error: 'Activity not found' });
  }

  activity.status = req.body.status || (activity.status === 'published' ? 'draft' : 'published');
  activity.updatedAt = new Date().toISOString();

  saveLocalDb(db);
  res.json(activity);
});

// GET Programmes
app.get('/api/programmes', (req: Request, res: Response) => {
  const db = loadLocalDb();
  res.json(db.programmes || INITIAL_PROGRAMMES);
});

// PUT Programme (Admin)
app.put('/api/programmes/:id', verifyAdminAuth, (req: Request, res: Response) => {
  const db = loadLocalDb();
  const index = db.programmes.findIndex((p: any) => p.id === req.params.id);
  if (index === -1) {
    return res.status(404).json({ error: 'Programme not found' });
  }

  db.programmes[index] = {
    ...db.programmes[index],
    ...req.body
  };

  saveLocalDb(db);
  res.json(db.programmes[index]);
});

// GET Gallery
app.get('/api/gallery', (req: Request, res: Response) => {
  const db = loadLocalDb();
  res.json(db.gallery || []);
});

// POST Gallery (Admin)
app.post('/api/gallery', verifyAdminAuth, (req: Request, res: Response) => {
  const db = loadLocalDb();
  const { title, category, imageUrl, caption, activityId } = req.body;

  if (!imageUrl) {
    return res.status(400).json({ error: 'Image URL is required' });
  }

  const newPhoto = {
    id: `gal-${Date.now()}`,
    title: title || 'Community Activity Photo',
    category: category || 'Community',
    imageUrl,
    caption: caption || '',
    activityId: activityId || null,
    createdAt: new Date().toISOString()
  };

  db.gallery.unshift(newPhoto);
  saveLocalDb(db);
  res.status(201).json(newPhoto);
});

// DELETE Gallery (Admin)
app.delete('/api/gallery/:id', verifyAdminAuth, (req: Request, res: Response) => {
  const db = loadLocalDb();
  db.gallery = db.gallery.filter((g: any) => g.id !== req.params.id);
  saveLocalDb(db);
  res.json({ message: 'Photo removed from gallery' });
});

// GET Stats
app.get('/api/stats', (req: Request, res: Response) => {
  const db = loadLocalDb();
  const activities = db.activities || [];
  const published = activities.filter((a: any) => a.status === 'published');

  const now = new Date();
  const currentMonth = now.getMonth();
  const currentYear = now.getFullYear();

  const activitiesThisMonth = published.filter((a: any) => {
    const d = new Date(a.activityDate);
    return d.getMonth() === currentMonth && d.getFullYear() === currentYear;
  }).length;

  let totalBeneficiaries = 0;
  let womenReached = 0;
  let childrenReached = 0;

  published.forEach((a: any) => {
    womenReached += Number(a.womenReached || 0);
    childrenReached += Number(a.childrenReached || 0);
    totalBeneficiaries += Number(a.beneficiariesTotal || (a.womenReached + a.childrenReached + (a.otherBeneficiaries || 0)));
  });

  res.json({
    totalActivities: published.length,
    activitiesThisMonth,
    womenReached,
    childrenReached,
    communitiesReached: 8, // Sironko & Bulambuli sub-counties
    totalPhotos: db.gallery ? db.gallery.length : 0,
    totalBeneficiaries
  });
});

// GET Website Content
app.get('/api/website-content', (req: Request, res: Response) => {
  const db = loadLocalDb();
  res.json(db.websiteContent || INITIAL_WEBSITE_CONTENT);
});

// POST Direct Contact Message (Public)
app.post('/api/contact/messages', (req: Request, res: Response) => {
  const { name, email, phone, subject, message } = req.body;
  if (!name || !message) {
    return res.status(400).json({ error: 'Name and message are required' });
  }

  const db = loadLocalDb();
  if (!db.messages) {
    db.messages = [];
  }

  const newMessage = {
    id: `msg_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
    name: name.trim(),
    email: (email || '').trim(),
    phone: (phone || '').trim(),
    subject: (subject || 'General Inquiry').trim(),
    message: message.trim(),
    createdAt: new Date().toISOString(),
    read: false
  };

  db.messages.unshift(newMessage);
  saveLocalDb(db);

  res.status(201).json({ success: true, message: 'Message sent successfully', data: newMessage });
});

// GET Direct Contact Messages (Admin)
app.get('/api/contact/messages', verifyAdminAuth, (req: Request, res: Response) => {
  const db = loadLocalDb();
  res.json(db.messages || []);
});

// PUT Toggle Read Status on Contact Message (Admin)
app.put('/api/contact/messages/:id/toggle-read', verifyAdminAuth, (req: Request, res: Response) => {
  const db = loadLocalDb();
  if (!db.messages) db.messages = [];
  const msg = db.messages.find((m: any) => m.id === req.params.id);
  if (!msg) {
    return res.status(404).json({ error: 'Message not found' });
  }
  msg.read = !msg.read;
  saveLocalDb(db);
  res.json(msg);
});

// DELETE Contact Message (Admin)
app.delete('/api/contact/messages/:id', verifyAdminAuth, (req: Request, res: Response) => {
  const db = loadLocalDb();
  if (!db.messages) db.messages = [];
  db.messages = db.messages.filter((m: any) => m.id !== req.params.id);
  saveLocalDb(db);
  res.json({ success: true, message: 'Message deleted successfully' });
});

// PUT Website Content Section (Admin)
app.put('/api/website-content/:section', verifyAdminAuth, (req: Request, res: Response) => {
  const db = loadLocalDb();
  const sectionKey = req.params.section;

  if (!db.websiteContent) {
    db.websiteContent = INITIAL_WEBSITE_CONTENT;
  }

  db.websiteContent[sectionKey] = {
    section: sectionKey,
    title: req.body.title || sectionKey,
    content: req.body.content || req.body,
    updatedAt: new Date().toISOString(),
    updatedBy: 'Administrator'
  };

  saveLocalDb(db);
  res.json(db.websiteContent[sectionKey]);
});

// POST Image Upload Endpoint
app.post('/api/upload', (req: Request, res: Response) => {
  const { imageBase64, filename } = req.body;

  if (!imageBase64) {
    return res.status(400).json({ error: 'No image data received' });
  }

  // Handle base64 string
  try {
    const uploadsDir = path.join(process.cwd(), 'public', 'uploads');
    if (!fs.existsSync(uploadsDir)) {
      fs.mkdirSync(uploadsDir, { recursive: true });
    }

    const matches = imageBase64.match(/^data:([A-Za-z-+\/]+);base64,(.+)$/);
    if (!matches || matches.length !== 3) {
      // If it's already a direct URL string, return it back
      if (imageBase64.startsWith('http')) {
        return res.json({ url: imageBase64 });
      }
      return res.status(400).json({ error: 'Invalid base64 format' });
    }

    const ext = matches[1].split('/')[1] || 'jpg';
    const cleanExt = ext.replace('+xml', '');
    const safeFilename = `buhugu_${Date.now()}_${Math.random().toString(36).substring(2, 7)}.${cleanExt}`;
    const filePath = path.join(uploadsDir, safeFilename);

    const buffer = Buffer.from(matches[2], 'base64');
    fs.writeFileSync(filePath, buffer);

    const publicUrl = `/uploads/${safeFilename}`;
    return res.json({ url: publicUrl, filename: safeFilename });
  } catch (err) {
    console.error('Upload handling error:', err);
    return res.status(500).json({ error: 'Failed to save uploaded photograph' });
  }
});

// Start Express + Vite Middleware
async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req: Request, res: Response) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Buhugu Living Hope Ministries Server running on http://localhost:${PORT}`);
  });
}

startServer();
